# Workflow for deploying PR previews to GitHub Pages
name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

# Prevent concurrent deployments for the same PR
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event.action != 'closed'

      - name: Setup Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        if: github.event.action != 'closed'
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Build with Jekyll
        if: github.event.action != 'closed'
        run: bundle exec jekyll build --baseurl "/pr-preview/pr-${{ github.event.number }}"
        env:
          JEKYLL_ENV: production

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.3
        with:
          source-dir: ./_site/
